# Generated by Django 4.0.5 on 2022-06-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_clubs_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='references',
        ),
    ]
