# Generated by Django 4.0.5 on 2022-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='references',
            field=models.ManyToManyField(related_name='candidates', to='users.referee'),
        ),
    ]
