# Generated by Django 4.0.5 on 2022-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_referee_phone_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.CharField(default='', max_length=250),
        ),
    ]
