# Generated by Django 4.0.5 on 2022-06-09 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_referee_phone_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='club',
            old_name='members',
            new_name='no_of_members',
        ),
        migrations.AlterField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(related_name='members', to='users.club'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=250)),
                ('tools', models.CharField(max_length=250)),
                ('personal', models.BooleanField(default=False)),
                ('hastags', models.ManyToManyField(related_name='projects', to='users.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(related_name='groups', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='group', to='users.project')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='projectees', to='users.project'),
        ),
    ]
