# Generated by Django 4.1 on 2022-08-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
