# Generated by Django 4.1 on 2022-08-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_teacher_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
    ]
