# Generated by Django 4.1.3 on 2022-11-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
