# Generated by Django 4.1.3 on 2022-11-18 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='', max_length=100)),
                ('shop_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='Website.location')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='seller_model', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('shops', models.ManyToManyField(related_name='items', to='Website.sellers')),
            ],
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_locations', to='Website.location')),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='buyer_model', to='users.user')),
            ],
        ),
    ]
