# Generated by Django 4.1.3 on 2022-11-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='phone',
        ),
    ]
